version: '3'

services:

  hassio:
    image: homeassistant/amd64-hassio-supervisor:latest
    container_name: hassio_supervisor
    privileged: true
    entrypoint: ["/bin/bash", "-c", echo "Resetting last boot..." && sed -i 's/"last_boot": ".*"/"last_boot": ""/' /data/config.json 2> /dev/null && echo "Starting hassio..." && python3 -m supervisor]
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/qemux86-64-homeassistant
      - SUPERVISOR_SHARE=${SUPERVISOR_SHARE}
      - SUPERVISOR_NAME=hassio_supervisor
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - ${SUPERVISOR_SHARE}:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
